---
- hosts: all 
  become: true 
  vars_files:
   - group_vars/usuario.yml
   - group_vars/var_basic.yml
  vars:
     add_user: true
     generate_key: false
  roles:
    - usuario
    - java
    - hadoop
